carthage_bootstrap:
	(cd Vendor && carthage bootstrap --platform ios --use-xcframeworks)
	rm -rf Vendor/Carthage/Checkouts

carthage_update:
	(cd Vendor && carthage update --platform ios --use-xcframeworks)
	rm -rf Vendor/Carthage/Checkouts
